### ISSUE TITLE
React integration is not working

### ISSUE THREAD

**Issue by batusai513** [ForsakenHarmony/parket#10]
Hi,

I've been toying with this library but I haven't make it work with react as intended, when using observe on a react component, modifying the store don't trigger a re-render.

I've created a sandbox for yo to check if I'm doing something wrong.

https://codesandbox.io/s/0ynxwn754w

Thanks in advanced for your help and effort for creating this lib.

**Comment by ForsakenHarmony** [comment]
should be fixed in 0.2.4, thanks for reporting it
