### ISSUE TITLE
Trouble accessing arrays via index

### ISSUE THREAD

**Issue by Jaden-Giordano** [ForsakenHarmony/parket#11]
I get `Cannot read property 'images' of undefined` when trying to call `console.log(store.featured[0].images);`. I'm using the `@connect` decorator and am able to grab 'loading' and call functions like map on the 'products' and features' arrays; I'm just not able to access via index on any of the arrays. In case I'm attempting to access these wrong here is my model code:
```
const Shop = model('Shop', {
  initial: () => ({
    loading: false,
    products: [],
  }),

  actions: self => ({
    async updateProducts() {
      self.loading = true;
      const rawProducts = await client.product.fetchAll().catch(() => []);
      self.loading = false;

      const products = Product.fromGraphModel(rawProducts);

      Object.assign(self, { products });
    },
  }),

  views: self => ({
    featured: () => (self.products.filter(product => product.tags.includes('featured'))),
  }),
});
```

**Comment by ForsakenHarmony** [comment]
which version are you using?

also why are you using object.assign?

**Comment by Jaden-Giordano** [comment]
Sorry about that, it was just a test I was running and forgot to switch it back; I've edited the post to use `self.loading = true`. I've tested it on both 0.2.4 and 0.3.0. This isn't super urgent because I'm not accessing variables this way, I just use it for testing, but I'm sure this may be an enhancement to debugging if it was possible.

**Comment by Jaden-Giordano** [comment]
I'm going to close this here and create the issue on the repo in charge of proxies.

**Comment by ForsakenHarmony** [comment]
wdym? proxies are a browser feature

**Comment by ForsakenHarmony** [comment]
also can't say I can reproduce

tried this
```
const Test = model("test", {
  initial: () => ({ loading: false, products: [] }),
  actions: self => ({
    update() {
      self.loading = true;
      setTimeout(() => {
        const products = [
          { tags: ["featured"], name: "test" },
          { tags: [], name: "wow" }
        ];
        self.loading = false;
        Object.assign(self, { products });
      }, 2000)
    }
  }),
  views: self => ({
    featured: () =>
      self.products.filter(product => product.tags.includes("featured"))
  })
});
```

**Comment by Jaden-Giordano** [comment]
Oh I guess there wouldn't really be anywhere for me to post that. The error seems to no longer persist testing it this morning, I'm not quite sure why it happened in the first place, but I've made a a lot of changes and it seems to work just fine with those changes. On second thought it most likely could have been me trying to check before loading was set to false and the products array being empty.

**Comment by ForsakenHarmony** [comment]
Yeah, possible seems like you were working on an empty array and any element of that is always undefined

I'll just close this, if you think there actually is an issue I can reopen
