### ISSUE TITLE
How to make models more strongly typed

### ISSUE THREAD

**Issue by berstend** [ForsakenHarmony/parket#15]
Thanks a lot for creating parket, I really enjoy using it!

I have a quick question regarding TypeScript usage and was wondering if you might have an idea how to best approach this.

Let's assume the following model (written in TypeScript):

```typescript
import model from 'parket'
import * as Types from '../common/types'

export const StateStore = model('State', {
  initial: () =>
    ({
      loading: true,
      connected: false,
    } as Types.GlobalState),
  actions: self => ({
    updateProps (config: Types.GlobalStateOpts) {
      Object.assign(self, config)
    }
  })
})

export interface StateStoreModel extends Model<Types.GlobalState> {
  updateProps: (config: Types.GlobalStateOpts) => void
}
```

If I now instantiate the model using the interface I can use the `updateProps` action with type support, despite `any` being used everywhere:
```typescript
const state = StateStore() as StateStoreModel
state.updateProps({ loading: false }) // with Intellisense
state.updateProps({ foobar: false }) // will throw error
```

I don't mind the extra verbosity of redeclaring the action method signatures. But I'm not sure my approach is the best here, as there's also the views and property values and I don't seem to find a good way to add those as well. 

Any idea how to improve on that? 😄 

Thanks!

**Comment by berstend** [comment]
The latest iteration of my attempt to make models more strongly typed:

```typescript
import model, { Model } from 'parket'
import * as Types from '../common/types'

interface StoreProps extends Types.GlobalState {}

interface StorePropsOpts extends Partial<StoreProps> {} // Partial makes everything optional

interface StoreActions {
  updateProps: (config: Types.GlobalStateOpts) => void
}
interface StoreViews {
  hasProblem: boolean
}

export const StateStore = model('State', {
  initial: () =>
    ({
      loading: true,
      connected: false,
      error: null,
    } as StoreProps),
  actions: self => ({
    updateProps (config: StorePropsOpts) {
      Object.assign(self, config)
    }
  }),
  views: self => ({
    hasProblem: () => self.error && !self.connected
  })
})

export interface StateStoreModel extends Model<Types.GlobalState>, StoreProps, StoreActions, StoreViews {}
```

Not optimal and still too verbose but something. :-)

**Comment by ForsakenHarmony** [comment]
have you tried the canary version? I had some problems getting typescript to work 100% and that seems to have improved typing a bit

**Comment by berstend** [comment]
Ah, nice! After upgrading with `yarn add parket@canary` the model properties are now recognized automatically by TypeScript.

The views and actions are still missing though. I'll see if I can find a way to add them to parket, though I'm still relatively new to typescript. :-)

**Comment by ForsakenHarmony** [comment]
Check the release notes, the API has changed a bit

**Comment by berstend** [comment]
Whoops, my bad - just noticed this. The new API looks amazing, modifying my models now.

**Comment by berstend** [comment]
PS: The `typings` in the [package.json](https://github.com/ForsakenHarmony/parket/blob/pre/package.json#L6) still point to `dist/index.d.ts`, had to manually change them to `dist/index_new.d.ts` for the API changes to be picked up. :)

**Comment by berstend** [comment]
After switching to the canary version and applying the patches from my PR above the experience has been very pleasant and TypeScript support just perfect 👍 

For reference, here's the discussed model with the new API:

```typescript
import model from 'parket'

export interface StateStoreProps {
  loading: boolean
  connected: boolean
  error: null | Error
}

const StoreProps = {
  loading: false,
  connected: false,
  error: null
} as StateStoreProps

export const StateStore = model('State', () => ({
  ...StoreProps,

  updateProps (props: Partial<StateStoreProps>) {
    Object.assign(this, props)
  },

  get hasProblem () {
    return this.error && !this.connected
  }
}))
```

I love the new API and as all tests stayed green rewrote all my models to it. ;-)

This issue was about ts support and can therefore be closed. Thanks! Looking forward to the 1.0 release.
