### ISSUE TITLE
Comparing to react-recollect

### ISSUE THREAD

**Issue by lishine** [ForsakenHarmony/parket#43]
Hi,

It is a very nice lib, which is immutable, it is similar in that respect to react-recollect but missing these features:
* connect to functional components
* afterUpdate

**Comment by ForsakenHarmony** [comment]
`functional components`
`observe` works for those?

`afterUpdate`
``` 
// you can subscribe to actions, patches (state updates) and snapshots (full state after actions)
const unsubscribe = instance.onSnapshot(console.log);
```
See also: https://github.com/ForsakenHarmony/parket/blob/master/examples/todo-mvc/src/index.js#L31

**Comment by lishine** [comment]
O, great! Very sorry, missed it...
And so observe can be used also to wrap functional component, great!

**Comment by ForsakenHarmony** [comment]
Yeah functional components aren't really documented, sorry about that
