### ISSUE TITLE
best way of working with async actions (question)

### ISSUE THREAD

**Issue by tinchoz49** [ForsakenHarmony/parket#6]
Hi @ForsakenHarmony! how are you? 

First of all, great work on this library. I really like it.

Well, my question is about how do you recommend work with async actions. 

I try to use async/await and it works really well but I don't know if this is the best approach in your library or you prefer something different.

This is my example:

```javascript
const delay = time => new Promise(resolve => setTimeout(resolve, time));
const TodoStore = model('TestStore', {
  initial: () => ({
    loading: false
  }),
  actions: self => ({
    delayFor: async time => {
      self.loading = true;
      await delay(time);
      self.loading = false;
    }
  })
});
```

**Comment by ForsakenHarmony** [comment]
Yeah, I do it the same way as you in the example

parket doesn't do anything with the return value of your actions, it just listens to state changes, so it's completely up to you

**Comment by tinchoz49** [comment]
that's awesome and I think it's something important to add in the readme because working with async patterns in other state managements always was a big deal and parket resolve this in a really simple and clean way.

Thanks for the quick response.

**Comment by ForsakenHarmony** [comment]
I've added a minimal example to the readme
